In [1]:
import numpy as np
import pandas as pd

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

In [4]:
df=pd.read_csv('train.csv')
df

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Fat_Content_LF,Item_Fat_Content_Low Fat,Item_Fat_Content_Regular,Item_Fat_Content_low fat,Item_Fat_Content_reg,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,6.800000,0.037490,48.6034,2004,291.6204,0,1,0,0,0,...,0,0,1,0,1,0,0,1,0,0
1,15.600000,0.172597,114.8518,1997,2163.1842,0,1,0,0,0,...,0,0,1,1,0,0,0,1,0,0
2,12.911575,0.054721,107.8254,1985,2387.5588,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
3,11.800000,0.098312,81.4618,1998,161.1236,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,17.850000,0.046600,125.1388,2004,1981.4208,0,0,1,0,0,...,0,0,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,7.970000,0.021579,105.9596,2002,2049.3324,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1360,13.800000,0.097611,54.8930,2007,679.1160,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1361,12.911575,0.010468,162.9526,1985,822.2630,0,1,0,0,0,...,0,0,1,1,0,0,1,0,0,0
1362,18.000000,0.015482,159.3604,2002,2059.9852,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1363,15.000000,0.162093,182.5266,2009,1290.9862,0,0,1,0,0,...,0,1,0,0,0,1,0,0,1,0

In [7]:
X=df.drop(columns='Item_Outlet_Sales',axis=1)
y=df['Item_Outlet_Sales']

In [8]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y=train_test_split(X,y,test_size=0.2)

In [12]:
lr=LinearRegression()

In [13]:
rfe=RFE(lr,10)

In [14]:
rfe.fit(train_X,train_y)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                               normalize=False),
    n_features_to_select=10, step=1, verbose=0)

In [15]:
rfe.support_

array([False,  True, False, False, False, False, False,  True, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False,  True,  True])

In [16]:
rfe.ranking_

array([25,  1, 23, 20, 17,  3,  2,  1, 19,  1,  1, 13, 10,  6, 26, 24, 18,
        1,  7, 12, 11,  1,  5, 14,  4,  8,  1, 21, 16,  9, 15,  1, 22,  1,
        1])